# Generated by Django 6.1.1 on 2026-09-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('fitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle_years',
            field=models.ManyToManyField(blank=True, related_name='products', through='fitment.Fitment', to='fitment.vehicleyear'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
    ]
