# Generated by Django 6.1.1 on 2026-09-13 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='fitment.vehiclemake')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('make', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='fitment.vehiclemodel')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('model', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, help_text="e.g. 'Front only', 'Requires bracket kit'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product')),
                ('vehicle_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='fitment.vehicleyear')),
            ],
            options={
                'unique_together': {('product', 'vehicle_year')},
            },
        ),
    ]
